server:
  port: 9090  # ??? ?? ??? ??

spring:
  application:
    name: instagram  # ?? properties ??? ?? ?? ??

  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root  # MySQL ???
    password: 1234  # MySQL ????
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 8.x ??? ? ???? ??

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # DB ??? ?? ???? (?? ?? ? ??, ???? validate ??)
    show-sql: true  # ???? SQL ?? ??? ??

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB  # ?? ??? ?? ??

  mustache:
    expose-session-attributes: true  # Mustache ????? ?? ? ?? ??

file:
  path: D:/Springboot-Instagram/upload/  # ?? ??? ?? ??
