server:
  port: 9090

spring:
  application:
    name: instagram

  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

jwt:
  secret: mySuperSecretKeyForInstagramProject2024LongEnough
  access-expiration: 3600000      # 1시간
  refresh-expiration: 604800000   # 7일

file:
  path: D:/Springboot-Instagram/upload/
